print("Kaila R. Moreno")
print("Brgy. Sayao, Mogpog, Marinduque")
print("May 6,2003")
print("CICS, BSI/T, 2B")
print("Watching sunset")
print("Listening music")
print("Watching movies")
print("Cleaning my room")
print("Reading books")